---

- name: Install docker packages
  yum:
    name: 
      - docker
      - python-docker
    state: present 

- name: Docker daemon running
  service:
    name: docker
    state: started

- name: Deploy container image
  docker_container:
    name: "api-{{ item }}"
    image: "10.10.12.117:5000/api-{{ student_user }}"
    ports:
      - "808{{ item}}: 8080"
    env:
      LANGUAGELAYER_API_KEY: "{{ lookup('file','/tmp/languagelayer_api_key') }}"
      ELASTICACHE: api-es.rdx8zv.0001.use1.cache.amazonaws.com
  loop: "{{ range(0, api_container_count, 1)|list }}"

- import_role:
    name: f5

