---
#
# Learning goals from this file:
#
#   1. Write your first Ansible automation
#   2. Become familiar with the standard Ansible module documentation
#


# Notice how the hosts keyword is now being used to limit the "blast radius" of
# our automation.
- hosts: web

  # These tasks must be executed as root, so this line uses sudo from our student account
  become: true
  
  tasks:

    # Task 1: Upgrade all packages currently on the host.  If you're a Linux admin,
    # this is the equivalent of a "yum update all"
    - name: Update all packages on host
      yum:
        name: '*'
        state: latest


    # Task 2: Install the Apache (httpd) package
    # Help: https://docs.ansible.com/ansible/latest/modules/yum_module.html
    - name: Install httpd
      yum:
        name: httpd
        state: present

 
    # Task 3: Start the Apache (httpd) service
    # Help: https://docs.ansible.com/ansible/latest/modules/service_module.html
    - name: Start httpd
      service:
        name: httpd
        state: started
 

