
- hosts: web
  name: Uninstall the Apache web service
  become: yes
  
  tasks:
    - name: Stop Apache
      service:
        name: httpd
        state: stopped
        
    - name: uninstall httpd package (httpd == Apache)
      yum:
        name: httpd
        state: absent
        
