---

- hosts: web
  name: Install the Apache web service
  become: yes
  vars:
    httpd_test_message: Hello, this is my test message
    httpd_port: 80
    httpd_packages:
      - httpd
      - mod_wsgi  
  
  tasks:
    
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ httpd_packages }}"    
    
    - name: set httpd port
      lineinfile:
         path: /etc/httpd/conf/httpd.conf
         regexp: "^Listen "
         line: "Listen {{ httpd_port }}"
         
    - name: Create web page
      template:
         src: index.html.j2
         dest: /var/www/html/index.html
        
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start httpd
      service:
        name: httpd
        state: started