---
#
# Learning goals from this file:
#
#   1. Introduce variables
#   2. Implement looping
#


- hosts: web
  name: Install the Apache web service
  become: true

  # Task 2.9: Define variables
  # We can define variables in a whopping 24 locations!  For now let's define a variable
  # right inline here.  It will be transparently consumed as part of a subsequent task.  Wondering how?
  # Open up the referenced file in the templates/ directory.
  vars:
    httpd_port: 80
  

  tasks:

    # Task 2.9: Install packages using a loop
    # Help: https://docs.ansible.com/ansible/latest/modules/yum_module.html
    # Help: https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html


    # Task 2: Configure httpd
    # Help: https://docs.ansible.com/ansible/latest/modules/template_module.html
    - name: Configure Apache
      template:
        src: templates/httpd.conf.j2
        dest: /etc/httpd/conf.d/httpd.conf

 
    # Task 3: Start the Apache (httpd) service
    # Help: https://docs.ansible.com/ansible/latest/modules/service_module.html
    - name: Start httpd
      service:
        name: httpd
        state: started
 
