---

- hosts: servers
  name: Common Server Configuration
  become: true

  roles: 
    # Task 3.1: Add common server role to your playbook
    - common_server


- hosts: web
  name: Web Server Configuration
  become: true

  roles: 
    # Task 3.5: Add web role to your playbook
    - web

