---

- name: Create api pool
  bigip_pool:
    provider:
      server: "{{ groups['loadbalancer'][0] }}"
      server_port: 8443
      validate_certs: no
      user: "{{ student_user }}"
      password: "{{ student_password }}"
    name: "{{ student_user }}-pool"
    lb_method: round-robin
    monitors: /Common/http
    monitor_type: and_list
  delegate_to: localhost

- name: Add pool members
  bigip_pool_member:
    provider:
      server: "{{ groups['loadbalancer'][0] }}"
      server_port: 8443
      validate_certs: no
      user: "{{ student_user }}"
      password: "{{ student_password }}"
    state: present
    host: "{{ inventory_hostname }}"
    port: "808{{ item }}"
    description: "{{ student_user }}-api-{{ item }}"
    pool: "{{ student_user }}-pool"
  loop: "{{ range(0, api_container_count, 1)|list }}"
  delegate_to: localhost

- name: Create VIP for pool
  bigip_virtual_server:
    provider:
      server: "{{ groups['loadbalancer'][0] }}"
      server_port: 8443
      validate_certs: no
      user: "{{ student_user }}"
      password: "{{ student_password }}"
    name: "{{ student_user }}-vip"
    destination: "{{ groups['loadbalancer'][0] }}"
    port: "80{{ '%02d'|format(student_number|int) }}"
    enabled_vlans: "all"
    all_profiles: ['http','oneconnect']
    pool: "{{ student_user }}-pool"
    snat: "Automap"
  delegate_to: localhost


