---
# tasks file for apache_basic

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ httpd_packages }}"

- name: Configure Apache
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^Listen "
    line: "Listen {{ httpd_port }}"
  notify: restart httpd

- name: Start httpd
  service:
    name: httpd
    state: started

- name: Create web page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

