---

- name: Install docker packages
  yum:
    name: 
      - docker
      - python-docker
    state: present 

- name: Docker daemon running
  service:
    name: docker
    state: started

- name: Deploy container image
  docker_container:
    name: api1
    image: "10.10.12.117:5000/api-{{ student_user }}"
    ports:
      - 8080:8080
    env:
      LANGUAGELAYER_API_KEY: "{{ lookup('file','/tmp/languagelayer_api_key') }}"

- import_role:
    name: f5

